services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6COr22YVy3KDOLwK
      POSTGRES_DB: uw-course-planner
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: ".env"
    networks:
      - proxynet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxynet
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: uw-course-planner
    env_file: ".env"
    networks:
      - proxynet
    depends_on:
      migration:
        condition: service_completed_successfully

networks:
  proxynet:
    name: proxynet
    external: true
