services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6COr22YVy3KDOLwK
      POSTGRES_DB: uw-course-planner
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: ".env.production"
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: uw-course-planner
    env_file: ".env.production"
